<<<<<<< Updated upstream
# Generated by Django 2.2.9 on 2020-08-28 08:24
=======
# Generated by Django 2.1 on 2020-08-28 06:17
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management', models.CharField(max_length=30)),
<<<<<<< Updated upstream
                ('S_address', models.TextField(null=True)),
                ('L_address', models.TextField(null=True)),
                ('purpose', models.TextField(null=True)),
                ('camera_num', models.IntegerField(null=True)),
                ('camera_pixel', models.IntegerField(null=True)),
                ('shoot_info', models.TextField(null=True)),
                ('storage_days', models.IntegerField(null=True)),
                ('installed_date', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('latitude', models.TextField(null=True)),
                ('longitude', models.TextField(null=True)),
                ('data_date', models.DateField(null=True)),
=======
                ('S_address', models.TextField()),
                ('L_address', models.TextField()),
                ('purpose', models.TextField()),
                ('camera_num', models.PositiveIntegerField()),
                ('camera_pixel', models.PositiveIntegerField()),
                ('shoot_info', models.TextField()),
                ('storage_days', models.PositiveIntegerField()),
                ('phone', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('data_date', models.DateField()),
>>>>>>> Stashed changes
                ('alarm', models.BooleanField(default=False)),
            ],
        ),
    ]
