# Generated by Django 2.2.9 on 2020-08-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management', models.CharField(max_length=30)),
                ('S_address', models.TextField()),
                ('L_address', models.TextField()),
                ('purpose', models.TextField()),
                ('camera_num', models.PositiveIntegerField()),
                ('camera_pixel', models.PositiveIntegerField()),
                ('shoot_info', models.TextField()),
                ('storage_days', models.PositiveIntegerField()),
                ('installed_date', models.TextField()),
                ('phone', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('data_date', models.TextField()),
            ],
        ),
    ]
