# Generated by Django 2.2.9 on 2020-09-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='alarm',
        ),
    ]
