# Generated by Django 2.2.9 on 2020-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='installed_date',
        ),
        migrations.AddField(
            model_name='location',
            name='alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='data_date',
            field=models.DateField(),
        ),
    ]
