# Generated by Django 2.1.3 on 2020-09-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField(null=True)),
                ('longitude', models.TextField(null=True)),
                ('location_pk', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('station', models.CharField(max_length=30)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
